### ISSUE TITLE
custom videos

### ISSUE THREAD

**Issue by IronicBadger** [cDima/Aerial#130]
Hi,

It'd be cool if I could add a folder of my own videos to randomly intermingle with the Apple footage. Is this possible?

**Comment by Sonartek** [comment]
I know it's certainly possible to _replace_ existing .MOV files with other types of movie files, so long as they're named the same.  For example, I pretty much hate b8-3.mov, so I downloaded "The Earth in 4k Extended Edition" from YouTube as a MP4 (https://youtu.be/7fYKMCCPh28), pulled the audio track out (because Aerial WILL play audio if it's in the video file!) and just _renamed_ (not re-encoded) the MP4 to b8-3.mov.  Now I get 1 hours of 4k space video shot from ISS as 1 movie in the Aerial library.  I haven't tried MKV's or other formats yet, from the CODEC cares more about the file contents than it does about the actual file extension, so there's ways to cheat your way around this if you really want.

**Comment by gaschu95** [comment]
On a multi-monitor setup it would be cool if it would only play videos that are in the same folder. So all the screens have the same theme if you group videos with similar themes into one folder.
