### ISSUE TITLE
It seems like Aerial doesnt delete the video playlist it creates when it runs

### ISSUE THREAD

**Issue by deucks** [cDima/Aerial#19]
In "groove music" down the left hand plane aerial seems to have created alot of playlists repeatedly when the screen saver starts
![aerial](https://cloud.githubusercontent.com/assets/8471807/10997134/af2143ba-84de-11e5-869d-244a88832e44.PNG)

**Comment by cDima** [comment]
@deucks  @matthiasg Please check the latest build, it should not create more Aerial playlists. You will have to delete the ones you have by hand. Direct link:  https://github.com/cDima/Aerial/blob/master/install/aerial.scr?raw=true 

If it works well I'll package it to the releases page.

**Comment by matthiasg** [comment]
Still happening. I installed it and let it run (and it created 6 playlists in my playlist folder)

**Comment by cDima** [comment]
Did you use the raw version from the repo?

**Comment by cDima** [comment]
@matthiasg I updated the current 0.2 release zip, please retry installing that. The current app does not have versioning anywhere in UI unfortunatelly.

**Comment by matthiasg** [comment]
i installed that version (sha1: 971327c22377526805ab2154f69bf7a8d26216bc) and it still creates a number of aerial playlists in my onedrive/music/playlist folder ... 

i do test though by installing it first. then starting the screensaver in the screensaver selection dialog. and ending it by pressing ESC. since you create them for the playback time it might be that your process doesnt close proberly etc... i dont have much time the next few days, but if you dont find anything specific i can try compiling it here and attaching a debugger or so.
- cheers

**Comment by cDima** [comment]
@matthiasg @deucks  please try the latest build v3 in https://github.com/cDima/Aerial/tree/master/install - it doesn't use playlists but should cycle through the videos well.

**Comment by matthiasg** [comment]
chrome said on download "Failed - Virus detected" -- duuh .. i will compile it myself then :)

**Comment by matthiasg** [comment]
tried it last week, and it works for me thanks
