### ISSUE TITLE
Problems with windows 10

### ISSUE THREAD

**Issue by furanshitsuko** [cDima/Aerial#3]
Sorry but i'm not a programer and i can't help you in this.  In windows 10 x64 don't work your saver, it's freeze and return to desktop screen.

**Comment by goncharov** [comment]
Hi. Try to install `Windows Media Player` via `Turn Windows features on or off`

**Comment by CaryFFF** [comment]
i have install windows media player,it also dont work in windows 10 x64

**Comment by cDima** [comment]
@CaryFFF Have you installed the .net framework 4.6?  https://support.microsoft.com/en-us/kb/2715633

**Comment by CaryFFF** [comment]
@cDima  yes,i have installed the .net framework 4.6

**Comment by spacentropy** [comment]
Win 10 x64 10.0.10240 doesn't work.  Windows Media Player Installed. Also, you can't install .NET Framework 4.6 because Windows 10 already has it out of the box.

**Comment by CaryFFF** [comment]
my version is  win10 x64 10576

**Comment by cDima** [comment]
What is the error steps to reproduce?

**Comment by spacentropy** [comment]
I don't know really. Do you happen to use Windows 10? I have just downloaded .scr and clicked "Install".
Then I received the error when I tried to start the screensaver. I checked what Microsoft suggests in that article - https://yadi.sk/i/I6dp5Q5OkFSwb 
Also on that page you've linked: 'You can't fix the configuration problem yourself. Contact the app vendor to resolve the issue.'

**Comment by evonbart** [comment]
Is there any reliable info about why it's triggering every AV software? And I don't mean from the developer - no offense. Has a reliable and impartial 3rd party, vetted the code? XCodeGhost comes to mind among others.

**Comment by Gatewayy** [comment]
It does NOT trigger any alerts with Kaspersky Internet Security FYI,

Brett Elliff

**Comment by alistairmcmillan** [comment]
@evonbart It doesn't trigger "every AV software". Version 1.1 triggers 11 out of 55. Version 1.2 triggers 4 out of 53. Notably the ones that do flag it pretty much almost all detect it as something generic which means they've just haven't found some specific known malware. It means their are using heuristics to look for suspicious behaviour and think they've found suspicious behaviour. For some reason screensavers regularly get flagged for suspicious behaviour. I've written a few screensavers myself and had similar problems in the past with them being flagged as malicious. Never been able to work out what is triggering the false positives.

And for what its worth, XCodeGhost doesn't make sense in this context. Firstly it was only present in applications that were compiled with a copy of Apple's developer tools sourced from a dubious source. But if anyone had vetted the code for those applications they wouldn't have found anything because the malicious code was inserted at compile time.
